version: '3.5'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phonebook
    volumes:
      - postgres:/data/postgres
    ports:
      - "54320:5432"

volumes:
  postgres: